contact/urls.py
from django.urls import path
from . import views
app_name = 'contact'
urlpatterns = [
    path('', views.get_contact, name='contact')
]

hoc/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('post/', include('post.urls')),
    path('contact/', include('contact.urls'))
]

home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.get_index),
    path('index/', views.get_index1, name='trangchu')
]

post/urls.py
from django.urls import path
from . import views
app_name = 'post'
urlpatterns = [
    path('', views.get_baiviet, name='baiviet')
]

contact/models.py
from django.db import models

# Create your models here.
class contactForm(models.Model):
    username = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()

home/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models

# Create your models here.

contact/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def get_contact(request):
    return render(request, 'contact/contact.html')

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def get_index(request):
    return HttpResponse('hi')
def get_index1(request):
    return render(request, 'home/index.html')
    

post/views.py
from django.shortcuts import render

# Create your views here.
def get_baiviet(request):
    return render(request, 'post/baiviet.html')

contact/templates/contact/contact.html
{% extends 'home/hi.html' %}
{% block noidung %}
    <h1>Đây là liên hệ</h1>
{% endblock %}

home/templates/home/hi.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'home/css/styles.css' %}">
</head>
<body>
    <a href="{% url 'home:trangchu' %}">home</a>
    <a href="{% url 'post:baiviet' %}">baiviet</a>
    <a href="{% url 'contact:contact'%}">contact</a>
    {% block noidung %}

    {% endblock %}
</body>
</html>

home/templates/home/index.html
{% extends 'home/hi.html' %}
{% block noidung %}
    <h1>Trang chủ</h1>
{% endblock %}

post/templates/post/baiviet.html
{% extends 'home/hi.html' %}
{%block noidung %}
    <h1> đây là bài viết</h1>
{% endblock %}  